server:
  port: 9090
---
spring:
  profiles: local,default
  h2:
    console:
           enabled: true
           path: /h2-console
           settings:
                   web-allow-others: false
                   trace: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
      url: jdbc:h2:~/test
      username: sa
      password: null
      driverClassName: org.h2.Driver
 